on:
  push:
    branches: [ "master" ]

name: build

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build-binary
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --all-targets